# Generated by Django 5.1.1 on 2024-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_category_unique_title_case_sensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
