# Generated by Django 5.1.1 on 2024-10-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring',
            field=models.CharField(max_length=45),
        ),
    ]
