# Generated by Django 5.1.1 on 2024-10-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
