# Generated by Django 5.1.1 on 2024-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_chat_created_at_alter_chat_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hours',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
