# Generated by Django 5.1.1 on 2024-10-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_task_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='tag',
        ),
    ]
