# Generated by Django 5.1.1 on 2024-10-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_rename_category_tag_rename_category_task_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['created_at']},
        ),
    ]
